-- ALTER TABLE SA1030 ALTER COLUMN A1_LOJA VARCHAR(2)
ALTER TABLE SA1030 ALTER COLUMN A1_LOJA VARCHAR(3)

-- ALTER TABLE SA1040 ALTER COLUMN A1_LOJA VARCHAR(2)
ALTER TABLE SA1040 ALTER COLUMN A1_LOJA VARCHAR(3)

-- DROP TABLE IF EXISTS ZZEXEMPLO
CREATE TABLE ZZEXEMPLO (...